# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170426_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(related_name='favorites', to='main.User'),
        ),
    ]
