# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
